### ISSUE TITLE
Have user make username at sign up

### ISSUE THREAD

**Issue by AndrewO777** [AndrewO777/ChatApp#8]

**Comment by cjl1197** [comment]
almost done here. i can change it later, but I have a pop up that I will run only one time, when the user first get's to the home page that will allow them to set their user name. then I plan to push those to a username db, so we can check if that username is already in use.

**Comment by cjl1197** [comment]
pop up was more hassle then it was worth. added the username to the sign-up page.

**Comment by cjl1197** [comment]
completed
